mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  passwd: 123456
  database: pokemon

MysqlTemplate: "%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local"

mongo:
  host: 127.0.0.1
  port: 27017
  username: root
  passwd: 123456
  database: pokemon

MongoTemplate: "mongodb://%s:%s@%s:%s/?ssl=false"