GET http://127.0.0.1:8080/v1/services/list
ApiToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNjA1MDIzMDM4NDEwMDY3OTY4LCJleHAiOjE2NzIxMDg4NTcsImlzcyI6Imp3dCJ9.Pp79uHHTlSX8NJueXm4cF5Zlkt7Ji6O51vW3YktSoeE
