POST http://127.0.0.1:8080/v1/API/create
Content-Type: application/json

{
  "Name":"postPing",
  "Path" : "/postPing",
  "ServiceId": 1589949221023256576,
  "Protocol": "http",
  "Method": "POST",
  "ConnectTimeout": 100000,
  "Retries": 1
}